pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/rishikaagrawal123/DEVOPSPROJECT-MONITORING-AS-CODE.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                sh 'docker-compose -f infrastructure/docker/docker-compose.yml up -d --build'
                
            }
        }

    }
}