pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/rishikaagrawal123/DEVOPSPROJECT-MONITORING-AS-CODE'
            }
        }

        stage('Configuration Management') {
            steps {
                // In a real environment, this would run puppet apply natively on the host
                // For this project presentation, we're demonstrating it using Puppet Docker container
                sh 'docker run --rm -v ${WORKSPACE}:/code -w /code puppet/puppet-agent-ubuntu apply infrastructure/puppet/manifests/monitoring.pp'
                git 'https://github.com/rishikaagrawal123/DEVOPSPROJECT-MONITORING-AS-CODE.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                sh 'docker-compose -f infrastructure/docker/docker-compose.yml up -d --build'
                
            }
        }

    }

}